CREATE DATABASE [2010];
GO
USE [2010];
GO

CREATE TABLE Wishes (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nickname NVARCHAR(100) NOT NULL,
    WishText NVARCHAR(500) NOT NULL,
    Hearts INT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE()
);
